### ISSUE TITLE
asking for csv when provided UC_INDEX_LIST and _RATIOS

### ISSUE THREAD

**Issue by punkpony** [Erastova-group/ClayCode#43]
if input is 

```
# required UCs to builder system as list
UC_INDEX_LIST: [D221 D228]

# probability list of unit cells in system
UC_RATIOS_LIST: [0.9 0.1]
```

still crashes because no .csv 

```

Reading 'Pyr1.yaml':

	OUTPATH = '/Users/valentina/Desktop/Hannah/ClayCode/Tutorial'
	SYSNAME = 'Pyr-1'
	BUILD = 'new'
	CLAY_TYPE = 'D21'
	X_CELLS = 6
	Y_CELLS = 4
	N_SHEETS = 2
	UC_INDEX_LIST = ['D221 D228']
	UC_RATIOS_LIST = ['0.9 0.1']
	IL_SOLV = False
	BOX_HEIGHT = 50
	BULK_SOLV = True
	BULK_IONS = {'Na': 0.3, 'Cl': 0.3}
	GMX = 'gmx'
Traceback (most recent call last):
  File "/Users/valentina/.local/bin/ClayCode", line 8, in <module>
    sys.exit(__main__.run())
  File "/Users/valentina/.local/pipx/venvs/claycode/lib/python3.9/site-packages/ClayCode/__main__.py", line 17, in run
    args = args_factory.init_subclass(args)
  File "/Users/valentina/.local/pipx/venvs/claycode/lib/python3.9/site-packages/ClayCode/core/parsing.py", line 912, in init_subclass
    return _cls(data)
  File "/Users/valentina/.local/pipx/venvs/claycode/lib/python3.9/site-packages/ClayCode/core/parsing.py", line 453, in __init__
    self.process()
  File "/Users/valentina/.local/pipx/venvs/claycode/lib/python3.9/site-packages/ClayCode/core/parsing.py", line 589, in process
    self.read_yaml()
  File "/Users/valentina/.local/pipx/venvs/claycode/lib/python3.9/site-packages/ClayCode/core/parsing.py", line 362, in wrapper
    return f(self)
  File "/Users/valentina/.local/pipx/venvs/claycode/lib/python3.9/site-packages/ClayCode/core/parsing.py", line 497, in read_yaml
    raise ValueError(
ValueError: No csv file with clay composition specified!
```

**Comment by hp115** [comment]
The 2 lists are combined in `UC_ID_RATIOS` and IL ions are given as `IL_IONS_RATIOS`. 
like this:
```
# ----------------------------------------------------------------------------
# Optional: Unit Cell Composition and Ratios input
# if not given, these will be calculated from data in the CLAY_COMP .csv file
# (Default no UC_INDEX_RATIOS specified)
# -----------------------------------------------------------------------------

# required UC indices and their ratios (ratios(tot): 1.00)
UC_INDEX_RATIOS:
  1: 0.5
  2: 0.5

IL_ION_RATIOS:
  Na: 0.5
  Ca: 0.5

# -----------------------------------------------------------------------------
```
